# cube_parser.py (v1.0 - Gaussian Cube File Parser for ORCA Orbital Visualization)
"""
Parses Gaussian cube format files generated by ORCA %plots.
Provides volumetric data for isosurface rendering of:
- Molecular orbitals (HOMO, LUMO)
- Total electron density
- Electrostatic potential

Cube format reference:
  Line 1-2: Comments
  Line 3: N_atoms, origin_x, origin_y, origin_z (Bohr)
  Line 4: N1, x1, y1, z1 (voxel count and step vector for axis 1)
  Line 5: N2, x2, y2, z2
  Line 6: N3, x3, y3, z3
  Lines 7..7+N_atoms: atom_number, charge, x, y, z
  Remaining: volumetric data (N1 * N2 * N3 values)
"""

import logging
import numpy as np
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Tuple, Optional

logger = logging.getLogger(__name__)

BOHR_TO_ANGSTROM = 0.529177249


@dataclass
class CubeData:
    """Parsed Gaussian cube file data"""
    comment1: str = ""
    comment2: str = ""
    n_atoms: int = 0
    origin: np.ndarray = field(default_factory=lambda: np.zeros(3))
    # Grid dimensions and step vectors
    n_steps: np.ndarray = field(default_factory=lambda: np.zeros(3, dtype=int))
    step_vectors: np.ndarray = field(default_factory=lambda: np.zeros((3, 3)))
    # Atom data
    atom_numbers: List[int] = field(default_factory=list)
    atom_charges: List[float] = field(default_factory=list)
    atom_positions: np.ndarray = field(default_factory=lambda: np.zeros((0, 3)))
    # Volumetric data (3D grid)
    data: np.ndarray = field(default_factory=lambda: np.zeros((0, 0, 0)))

    @property
    def origin_angstrom(self) -> np.ndarray:
        return self.origin * BOHR_TO_ANGSTROM

    @property
    def step_sizes_angstrom(self) -> np.ndarray:
        """Step size in Angstrom for each axis"""
        return np.array([
            np.linalg.norm(self.step_vectors[i]) * BOHR_TO_ANGSTROM
            for i in range(3)
        ])

    @property
    def grid_axes(self) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Return x, y, z coordinate arrays (in Angstrom) for the grid"""
        axes = []
        for i in range(3):
            step = np.linalg.norm(self.step_vectors[i]) * BOHR_TO_ANGSTROM
            start = self.origin[i] * BOHR_TO_ANGSTROM
            axes.append(np.linspace(start, start + step * (self.n_steps[i] - 1), self.n_steps[i]))
        return tuple(axes)

    @property
    def extent_angstrom(self) -> Tuple[Tuple[float, float], Tuple[float, float], Tuple[float, float]]:
        """Min/max extent of the grid in Angstrom"""
        axes = self.grid_axes
        return tuple((ax[0], ax[-1]) for ax in axes)


def parse_cube_file(filepath: Path) -> Optional[CubeData]:
    """
    Parse a Gaussian cube file.

    Args:
        filepath: Path to .cube file

    Returns:
        CubeData object or None on failure
    """
    filepath = Path(filepath)
    if not filepath.exists():
        logger.warning("Cube file not found: %s", filepath)
        return None

    try:
        with open(filepath, 'r', encoding="utf-8", errors="replace") as f:
            lines = f.readlines()

        cube = CubeData()
        idx = 0

        # Lines 1-2: Comments
        cube.comment1 = lines[idx].strip(); idx += 1
        cube.comment2 = lines[idx].strip(); idx += 1

        # Line 3: N_atoms, origin_x, origin_y, origin_z
        parts = lines[idx].split(); idx += 1
        cube.n_atoms = abs(int(parts[0]))
        cube.origin = np.array([float(parts[1]), float(parts[2]), float(parts[3])])

        # Lines 4-6: Grid dimensions and step vectors
        n_steps = np.zeros(3, dtype=int)
        step_vectors = np.zeros((3, 3))
        for i in range(3):
            parts = lines[idx].split(); idx += 1
            n_steps[i] = int(parts[0])
            step_vectors[i] = [float(parts[1]), float(parts[2]), float(parts[3])]
        cube.n_steps = n_steps
        cube.step_vectors = step_vectors

        # Lines 7..7+N_atoms: Atom data
        atom_numbers = []
        atom_charges = []
        positions = []
        for _ in range(cube.n_atoms):
            parts = lines[idx].split(); idx += 1
            atom_numbers.append(int(parts[0]))
            atom_charges.append(float(parts[1]))
            positions.append([float(parts[2]), float(parts[3]), float(parts[4])])
        cube.atom_numbers = atom_numbers
        cube.atom_charges = atom_charges
        cube.atom_positions = np.array(positions) if positions else np.zeros((0, 3))

        # Remaining lines: Volumetric data
        all_values = []
        for line in lines[idx:]:
            vals = line.split()
            for v in vals:
                try:
                    all_values.append(float(v))
                except ValueError as e:
                    logger.warning("Failed to parse cube voxel value: %s", e)

        expected = int(n_steps[0]) * int(n_steps[1]) * int(n_steps[2])
        if len(all_values) < expected:
            logger.warning("Cube voxel count short: got %d values, expected %d",
                           len(all_values), expected)
            all_values.extend([0.0] * (expected - len(all_values)))

        cube.data = np.array(all_values[:expected]).reshape(
            int(n_steps[0]), int(n_steps[1]), int(n_steps[2])
        )

        logger.info(
            "Parsed cube %s: grid=%dx%dx%d, atoms=%d, data range=[%.4e, %.4e]",
            filepath.name, n_steps[0], n_steps[1], n_steps[2],
            cube.n_atoms, cube.data.min(), cube.data.max(),
        )

        return cube

    except Exception as e:
        logger.warning("Error parsing cube %s: %s", filepath, e)
        return None


def extract_isosurface(cube: CubeData, isovalue: float = 0.02) -> Tuple[np.ndarray, np.ndarray]:
    """
    Extract isosurface vertices and faces using marching cubes.
    Falls back to contour slices if scikit-image is not available.

    Args:
        cube: CubeData object
        isovalue: Isosurface threshold value

    Returns:
        (vertices, faces) arrays for 3D rendering
    """
    try:
        from skimage.measure import marching_cubes
        # [FIX-ISO-002] Guard: check data has sufficient range for the isovalue
        data_min, data_max = cube.data.min(), cube.data.max()
        if not (data_min < isovalue < data_max):
            # Isovalue outside data range — no surface exists
            return np.zeros((0, 3)), np.zeros((0, 3), dtype=int)
        verts, faces, normals, values = marching_cubes(cube.data, level=isovalue)

        # Scale vertices to Angstrom coordinates
        step_sizes = cube.step_sizes_angstrom
        origin = cube.origin_angstrom
        verts_scaled = verts * step_sizes + origin

        return verts_scaled, faces

    except ImportError:
        logger.warning("scikit-image not available, using fallback contour extraction")
        return _fallback_isosurface(cube, isovalue)
    except Exception as e:
        logger.warning("marching_cubes error: %s, using fallback", e)
        return _fallback_isosurface(cube, isovalue)


def _fallback_isosurface(cube: CubeData, isovalue: float) -> Tuple[np.ndarray, np.ndarray]:
    """
    Fallback isosurface extraction without scikit-image.

    [FIX-FROG-EGG-004] Complete rewrite: numpy-only marching cubes implementation
    that produces a proper triangulated mesh. Falls back to Delaunay/ConvexHull
    if the simple MC fails, and finally to edge-crossing point cloud + ConvexHull.

    Strategy:
    1. Numpy-only marching cubes (simplified but correct)
    2. Scipy Delaunay triangulation of edge-crossing points
    3. Scipy ConvexHull of edge-crossing points
    4. Final: return points with no faces (scatter mode — last resort)
    """
    step_sizes = cube.step_sizes_angstrom
    origin = cube.origin_angstrom
    data = cube.data
    ni, nj, nk = data.shape

    # --- Attempt 1: Simplified marching cubes (numpy only) ---
    # For each voxel, check all 12 edges for sign changes and interpolate vertices.
    # Then use a simplified lookup to triangulate.
    try:
        verts, faces = _numpy_marching_cubes(data, isovalue, origin, step_sizes)
        if len(verts) > 0 and len(faces) > 0:
            return verts, faces
    except Exception as e:
        logger.warning("Numpy marching cubes fallback failed: %s", e)

    # --- Attempt 2: Edge-crossing points + triangulation ---
    points = _collect_edge_crossing_points(data, isovalue, origin, step_sizes)
    if not points:
        return np.zeros((0, 3)), np.zeros((0, 3), dtype=int)

    verts = np.array(points)

    if len(verts) >= 4:
        # Try Delaunay
        try:
            from scipy.spatial import Delaunay
            tri = Delaunay(verts)
            from collections import Counter
            face_count = Counter()
            for simplex in tri.simplices:
                for i in range(4):
                    face = tuple(sorted([simplex[j] for j in range(4) if j != i]))
                    face_count[face] += 1
            surface_faces = [list(f) for f, count in face_count.items() if count == 1]
            if surface_faces:
                return verts, np.array(surface_faces, dtype=int)
        except (ImportError, Exception) as e:
            logger.warning("Delaunay triangulation fallback failed: %s", e)

        # Try ConvexHull
        try:
            from scipy.spatial import ConvexHull
            hull = ConvexHull(verts)
            return verts, hull.simplices.copy()
        except (ImportError, Exception) as e:
            logger.warning("ConvexHull fallback failed: %s", e)

    # Final fallback: scatter points (no faces)
    return verts, np.zeros((0, 3), dtype=int)


def _collect_edge_crossing_points(data, isovalue, origin, step_sizes):
    """Collect linearly-interpolated crossing points along grid edges."""
    ni, nj, nk = data.shape
    points = []
    stride = max(1, min(ni, nj, nk) // 50)

    for i in range(0, ni - 1, stride):
        for j in range(0, nj - 1, stride):
            for k in range(0, nk - 1, stride):
                val = data[i, j, k]
                # Check 3 positive-direction edges
                for di, dj, dk in ((1, 0, 0), (0, 1, 0), (0, 0, 1)):
                    ni2, nj2, nk2 = i + di, j + dj, k + dk
                    if ni2 >= data.shape[0] or nj2 >= data.shape[1] or nk2 >= data.shape[2]:
                        continue
                    nval = data[ni2, nj2, nk2]
                    if (val - isovalue) * (nval - isovalue) < 0:
                        # Linear interpolation
                        denom = val - nval
                        if abs(denom) < 1e-15:
                            t = 0.5
                        else:
                            t = (val - isovalue) / denom
                        t = max(0.0, min(1.0, t))
                        x = origin[0] + (i + di * t) * step_sizes[0]
                        y = origin[1] + (j + dj * t) * step_sizes[1]
                        z = origin[2] + (k + dk * t) * step_sizes[2]
                        points.append([x, y, z])
    return points


def _numpy_marching_cubes(data, isovalue, origin, step_sizes):
    """Simplified numpy-only marching cubes producing triangulated mesh.

    Uses vectorized edge detection + per-edge vertex interpolation,
    then connects vertices sharing the same voxel into triangle fans.

    This is a simplified version that:
    1. Finds all voxels where at least one edge crosses the isovalue
    2. For each such voxel, collects interpolated vertices on crossing edges
    3. Creates a triangle fan from the centroid of those vertices

    Not as precise as full 256-case MC, but produces smooth connected meshes.
    """
    ni, nj, nk = data.shape
    if ni < 2 or nj < 2 or nk < 2:
        return np.zeros((0, 3)), np.zeros((0, 3), dtype=int)

    # Binary field: 1 where data >= isovalue, 0 otherwise
    binary = (data >= isovalue).astype(np.int8)

    # Find edges with sign changes along each axis
    # X-edges: between (i, j, k) and (i+1, j, k)
    x_cross = binary[:-1, :, :] != binary[1:, :, :]
    y_cross = binary[:, :-1, :] != binary[:, 1:, :]
    z_cross = binary[:, :, :-1] != binary[:, :, 1:]

    all_verts = []
    vert_voxel_ids = []  # which voxel each vertex belongs to

    def _interp_edge(i0, j0, k0, i1, j1, k1):
        """Linearly interpolate position along an edge."""
        v0 = data[i0, j0, k0]
        v1 = data[i1, j1, k1]
        denom = v0 - v1
        if abs(denom) < 1e-15:
            t = 0.5
        else:
            t = (v0 - isovalue) / denom
        t = max(0.0, min(1.0, t))
        x = origin[0] + (i0 + (i1 - i0) * t) * step_sizes[0]
        y = origin[1] + (j0 + (j1 - j0) * t) * step_sizes[1]
        z = origin[2] + (k0 + (k1 - k0) * t) * step_sizes[2]
        return (x, y, z)

    # Collect crossing positions for x-edges
    xi, xj, xk = np.where(x_cross)
    for idx in range(len(xi)):
        i, j, k = int(xi[idx]), int(xj[idx]), int(xk[idx])
        v = _interp_edge(i, j, k, i + 1, j, k)
        all_verts.append(v)
        vert_voxel_ids.append((i, j, k))

    # y-edges
    yi, yj, yk = np.where(y_cross)
    for idx in range(len(yi)):
        i, j, k = int(yi[idx]), int(yj[idx]), int(yk[idx])
        v = _interp_edge(i, j, k, i, j + 1, k)
        all_verts.append(v)
        vert_voxel_ids.append((i, j, k))

    # z-edges
    zi, zj, zk = np.where(z_cross)
    for idx in range(len(zi)):
        i, j, k = int(zi[idx]), int(zj[idx]), int(zk[idx])
        v = _interp_edge(i, j, k, i, j, k + 1)
        all_verts.append(v)
        vert_voxel_ids.append((i, j, k))

    if len(all_verts) < 3:
        return np.zeros((0, 3)), np.zeros((0, 3), dtype=int)

    # Limit total vertices to avoid memory explosion on large grids
    MAX_VERTS = 200000
    if len(all_verts) > MAX_VERTS:
        # Downsample: keep every Nth vertex
        step = len(all_verts) // MAX_VERTS + 1
        all_verts = all_verts[::step]
        vert_voxel_ids = vert_voxel_ids[::step]

    verts = np.array(all_verts, dtype=np.float64)

    # Group vertices by voxel and create triangle fans
    from collections import defaultdict
    voxel_to_verts = defaultdict(list)
    for vi, voxel_id in enumerate(vert_voxel_ids):
        voxel_to_verts[voxel_id].append(vi)

    faces = []
    for voxel_id, vert_indices in voxel_to_verts.items():
        n = len(vert_indices)
        if n >= 3:
            # Triangle fan from first vertex
            for t in range(1, n - 1):
                faces.append([vert_indices[0], vert_indices[t], vert_indices[t + 1]])

    if not faces:
        return verts, np.zeros((0, 3), dtype=int)

    return verts, np.array(faces, dtype=int)


def get_slice_data(cube: CubeData, axis: int = 2, slice_idx: int = None) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Get a 2D slice through the volumetric data for contour plotting.

    Args:
        cube: CubeData
        axis: 0=X, 1=Y, 2=Z (slice normal direction)
        slice_idx: Index along the axis (default: middle)

    Returns:
        (X_2d, Y_2d, values_2d) for contour/contourf plotting
    """
    if slice_idx is None:
        slice_idx = cube.n_steps[axis] // 2

    axes = cube.grid_axes
    data = cube.data

    if axis == 0:
        vals = data[slice_idx, :, :]
        ax1, ax2 = axes[1], axes[2]
        labels = ('Y (Å)', 'Z (Å)')
    elif axis == 1:
        vals = data[:, slice_idx, :]
        ax1, ax2 = axes[0], axes[2]
        labels = ('X (Å)', 'Z (Å)')
    else:
        vals = data[:, :, slice_idx]
        ax1, ax2 = axes[0], axes[1]
        labels = ('X (Å)', 'Y (Å)')

    X, Y = np.meshgrid(ax1, ax2)
    return X, Y, vals.T, labels
