# cube_parser.py (v1.0 - Gaussian Cube File Parser for ORCA Orbital Visualization)
"""
Parses Gaussian cube format files generated by ORCA %plots.
Provides volumetric data for isosurface rendering of:
- Molecular orbitals (HOMO, LUMO)
- Total electron density
- Electrostatic potential

Cube format reference:
  Line 1-2: Comments
  Line 3: N_atoms, origin_x, origin_y, origin_z (Bohr)
  Line 4: N1, x1, y1, z1 (voxel count and step vector for axis 1)
  Line 5: N2, x2, y2, z2
  Line 6: N3, x3, y3, z3
  Lines 7..7+N_atoms: atom_number, charge, x, y, z
  Remaining: volumetric data (N1 * N2 * N3 values)
"""

import numpy as np
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Tuple, Optional

BOHR_TO_ANGSTROM = 0.529177249


@dataclass
class CubeData:
    """Parsed Gaussian cube file data"""
    comment1: str = ""
    comment2: str = ""
    n_atoms: int = 0
    origin: np.ndarray = field(default_factory=lambda: np.zeros(3))
    # Grid dimensions and step vectors
    n_steps: np.ndarray = field(default_factory=lambda: np.zeros(3, dtype=int))
    step_vectors: np.ndarray = field(default_factory=lambda: np.zeros((3, 3)))
    # Atom data
    atom_numbers: List[int] = field(default_factory=list)
    atom_charges: List[float] = field(default_factory=list)
    atom_positions: np.ndarray = field(default_factory=lambda: np.zeros((0, 3)))
    # Volumetric data (3D grid)
    data: np.ndarray = field(default_factory=lambda: np.zeros((0, 0, 0)))

    @property
    def origin_angstrom(self) -> np.ndarray:
        return self.origin * BOHR_TO_ANGSTROM

    @property
    def step_sizes_angstrom(self) -> np.ndarray:
        """Step size in Angstrom for each axis"""
        return np.array([
            np.linalg.norm(self.step_vectors[i]) * BOHR_TO_ANGSTROM
            for i in range(3)
        ])

    @property
    def grid_axes(self) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Return x, y, z coordinate arrays (in Angstrom) for the grid"""
        axes = []
        for i in range(3):
            step = np.linalg.norm(self.step_vectors[i]) * BOHR_TO_ANGSTROM
            start = self.origin[i] * BOHR_TO_ANGSTROM
            axes.append(np.linspace(start, start + step * (self.n_steps[i] - 1), self.n_steps[i]))
        return tuple(axes)

    @property
    def extent_angstrom(self) -> Tuple[Tuple[float, float], Tuple[float, float], Tuple[float, float]]:
        """Min/max extent of the grid in Angstrom"""
        axes = self.grid_axes
        return tuple((ax[0], ax[-1]) for ax in axes)


def parse_cube_file(filepath: Path) -> Optional[CubeData]:
    """
    Parse a Gaussian cube file.

    Args:
        filepath: Path to .cube file

    Returns:
        CubeData object or None on failure
    """
    filepath = Path(filepath)
    if not filepath.exists():
        print(f"[CubeParser] File not found: {filepath}")
        return None

    try:
        with open(filepath, 'r') as f:
            lines = f.readlines()

        cube = CubeData()
        idx = 0

        # Lines 1-2: Comments
        cube.comment1 = lines[idx].strip(); idx += 1
        cube.comment2 = lines[idx].strip(); idx += 1

        # Line 3: N_atoms, origin_x, origin_y, origin_z
        parts = lines[idx].split(); idx += 1
        cube.n_atoms = abs(int(parts[0]))
        cube.origin = np.array([float(parts[1]), float(parts[2]), float(parts[3])])

        # Lines 4-6: Grid dimensions and step vectors
        n_steps = np.zeros(3, dtype=int)
        step_vectors = np.zeros((3, 3))
        for i in range(3):
            parts = lines[idx].split(); idx += 1
            n_steps[i] = int(parts[0])
            step_vectors[i] = [float(parts[1]), float(parts[2]), float(parts[3])]
        cube.n_steps = n_steps
        cube.step_vectors = step_vectors

        # Lines 7..7+N_atoms: Atom data
        atom_numbers = []
        atom_charges = []
        positions = []
        for _ in range(cube.n_atoms):
            parts = lines[idx].split(); idx += 1
            atom_numbers.append(int(parts[0]))
            atom_charges.append(float(parts[1]))
            positions.append([float(parts[2]), float(parts[3]), float(parts[4])])
        cube.atom_numbers = atom_numbers
        cube.atom_charges = atom_charges
        cube.atom_positions = np.array(positions) if positions else np.zeros((0, 3))

        # Remaining lines: Volumetric data
        all_values = []
        for line in lines[idx:]:
            vals = line.split()
            for v in vals:
                try:
                    all_values.append(float(v))
                except ValueError:
                    pass

        expected = int(n_steps[0]) * int(n_steps[1]) * int(n_steps[2])
        if len(all_values) < expected:
            print(f"[CubeParser] Warning: got {len(all_values)} values, expected {expected}")
            all_values.extend([0.0] * (expected - len(all_values)))

        cube.data = np.array(all_values[:expected]).reshape(
            int(n_steps[0]), int(n_steps[1]), int(n_steps[2])
        )

        print(f"[CubeParser] Parsed {filepath.name}: "
              f"grid={n_steps[0]}x{n_steps[1]}x{n_steps[2]}, "
              f"atoms={cube.n_atoms}, "
              f"data range=[{cube.data.min():.4e}, {cube.data.max():.4e}]")

        return cube

    except Exception as e:
        print(f"[CubeParser] Error parsing {filepath}: {e}")
        import traceback
        traceback.print_exc()
        return None


def extract_isosurface(cube: CubeData, isovalue: float = 0.02) -> Tuple[np.ndarray, np.ndarray]:
    """
    Extract isosurface vertices and faces using marching cubes.
    Falls back to contour slices if scikit-image is not available.

    Args:
        cube: CubeData object
        isovalue: Isosurface threshold value

    Returns:
        (vertices, faces) arrays for 3D rendering
    """
    try:
        from skimage.measure import marching_cubes
        verts, faces, normals, values = marching_cubes(cube.data, level=isovalue)

        # Scale vertices to Angstrom coordinates
        step_sizes = cube.step_sizes_angstrom
        origin = cube.origin_angstrom
        verts_scaled = verts * step_sizes + origin

        return verts_scaled, faces

    except ImportError:
        print("[CubeParser] scikit-image not available, using fallback contour extraction")
        return _fallback_isosurface(cube, isovalue)


def _fallback_isosurface(cube: CubeData, isovalue: float) -> Tuple[np.ndarray, np.ndarray]:
    """
    Fallback isosurface extraction without scikit-image.
    Samples points where |data| crosses the isovalue threshold.
    """
    step_sizes = cube.step_sizes_angstrom
    origin = cube.origin_angstrom
    data = cube.data

    points = []
    nx, ny, nz = data.shape

    # Sample every other point for speed
    stride = max(1, min(nx, ny, nz) // 30)
    for i in range(0, nx - 1, stride):
        for j in range(0, ny - 1, stride):
            for k in range(0, nz - 1, stride):
                val = data[i, j, k]
                # Check if isovalue crosses at this voxel
                neighbors = [
                    data[min(i + 1, nx - 1), j, k],
                    data[i, min(j + 1, ny - 1), k],
                    data[i, j, min(k + 1, nz - 1)],
                ]
                for nval in neighbors:
                    if (val - isovalue) * (nval - isovalue) < 0:
                        x = origin[0] + i * step_sizes[0]
                        y = origin[1] + j * step_sizes[1]
                        z = origin[2] + k * step_sizes[2]
                        points.append([x, y, z])
                        break

    if not points:
        return np.zeros((0, 3)), np.zeros((0, 3), dtype=int)

    verts = np.array(points)
    # No face connectivity for fallback - return empty faces
    faces = np.zeros((0, 3), dtype=int)
    return verts, faces


def get_slice_data(cube: CubeData, axis: int = 2, slice_idx: int = None) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Get a 2D slice through the volumetric data for contour plotting.

    Args:
        cube: CubeData
        axis: 0=X, 1=Y, 2=Z (slice normal direction)
        slice_idx: Index along the axis (default: middle)

    Returns:
        (X_2d, Y_2d, values_2d) for contour/contourf plotting
    """
    if slice_idx is None:
        slice_idx = cube.n_steps[axis] // 2

    axes = cube.grid_axes
    data = cube.data

    if axis == 0:
        vals = data[slice_idx, :, :]
        ax1, ax2 = axes[1], axes[2]
        labels = ('Y (Å)', 'Z (Å)')
    elif axis == 1:
        vals = data[:, slice_idx, :]
        ax1, ax2 = axes[0], axes[2]
        labels = ('X (Å)', 'Z (Å)')
    else:
        vals = data[:, :, slice_idx]
        ax1, ax2 = axes[0], axes[1]
        labels = ('X (Å)', 'Y (Å)')

    X, Y = np.meshgrid(ax1, ax2)
    return X, Y, vals.T, labels
