import requests
import time
import subprocess
import sys
import os
import json
import random
import copy
from datetime import datetime
from PIL import ImageGrab

# Configuration
MCP_SERVER_URL = "http://127.0.0.1:8000"
PYTHON_EXECUTABLE = sys.executable
SERVER_SCRIPT = os.path.join("agents", "mcp_server", "server.py")
CHEMGRID_SCRIPT = os.path.join("agents", "10_testing_build", "integrated", "draw.py")
LOG_DIR = "training_logs"
FAIL_LOG = os.path.join(LOG_DIR, "failed_attempts.json")
SUCCESS_LOG = os.path.join(LOG_DIR, "success_patterns.json")
CAPTURE_DIR = os.path.join(LOG_DIR, "captures")
CURRENT_STATE_FILE = os.path.join("c:/chemgrid", "current_state.json")

# Ensure log directories exist
os.makedirs(LOG_DIR, exist_ok=True)
os.makedirs(CAPTURE_DIR, exist_ok=True)

def kill_port_8000():
    """Kill any process listening on port 8000."""
    print("Checking for processes on port 8000...")
    try:
        cmd = "netstat -ano | findstr :8000"
        output = subprocess.check_output(cmd, shell=True).decode()
        lines = output.strip().split('\n')
        for line in lines:
            parts = line.split()
            if len(parts) >= 5:
                pid = parts[-1]
                if pid != "0":
                    print(f"Killing PID {pid} using port 8000...")
                    os.system(f"taskkill /F /PID {pid}")
    except:
        pass

def ensure_chemgrid_running():
    """Start ChemGrid if needed."""
    print(f"Launching ChemGrid from {CHEMGRID_SCRIPT}...")
    if not os.path.exists(CHEMGRID_SCRIPT):
        print(f"ERROR: ChemGrid script not found at {CHEMGRID_SCRIPT}")
        return False
        
    try:
        subprocess.Popen([PYTHON_EXECUTABLE, CHEMGRID_SCRIPT])
        print("ChemGrid launch command sent. Waiting for window initialization (8s)...")
        time.sleep(8) 
        return True
    except Exception as e:
        print(f"Failed to start ChemGrid: {e}")
        return False

def capture_screen(label):
    """Capture screen for debugging."""
    try:
        timestamp = datetime.now().strftime("%H%M%S")
        filename = f"{CAPTURE_DIR}/{label}_{timestamp}.png"
        ImageGrab.grab().save(filename)
    except Exception as e:
        print(f"Capture failed: {e}")

class ActionMutator:
    def __init__(self):
        self.mutation_rate = 0.3
        self.grid_noise = 1 

    def mutate(self, actions):
        """Apply random variations."""
        new_actions = copy.deepcopy(actions)
        for action in new_actions:
            if random.random() < self.mutation_rate:
                if "x" in action:
                    action["x"] += random.randint(-self.grid_noise, self.grid_noise)
                if "y" in action:
                    action["y"] += random.randint(-self.grid_noise, self.grid_noise)
                if "start_x" in action:
                    action["start_x"] += random.randint(-self.grid_noise, self.grid_noise)
                    action["start_y"] += random.randint(-self.grid_noise, self.grid_noise)
                    action["end_x"] += random.randint(-self.grid_noise, self.grid_noise)
                    action["end_y"] += random.randint(-self.grid_noise, self.grid_noise)
        return new_actions

def log_attempt(level, attempt, actions, target, actual, success, reason=""):
    entry = {
        "timestamp": datetime.now().isoformat(),
        "level": level,
        "attempt": attempt,
        "success": success,
        "target_smiles": target,
        "actual_smiles": actual,
        "actions_used": actions,
        "reason": reason
    }
    
    file_path = SUCCESS_LOG if success else FAIL_LOG
    try:
        if os.path.exists(file_path):
            with open(file_path, 'r') as f: data = json.load(f)
        else: data = []
        data.append(entry)
        with open(file_path, 'w') as f: json.dump(data, f, indent=2)
    except Exception as e:
        print(f"Logging failed: {e}")

def get_current_smiles():
    """Read current SMILES from file generated by ChemGrid."""
    try:
        if os.path.exists(CURRENT_STATE_FILE):
            with open(CURRENT_STATE_FILE, "r") as f:
                data = json.load(f)
                return data.get("smiles", ""), data.get("atom_count", 0)
    except Exception as e:
        print(f"Error reading state: {e}")
    return "", 0

def validate_smiles(target, current):
    """Validate SMILES match using server."""
    try:
        resp = requests.post(f"{MCP_SERVER_URL}/validate/smiles", 
                             params={"current_smiles": current, "target_smiles": target})
        if resp.status_code == 200:
            return resp.json().get("match", False)
    except:
        pass
    # Fallback basic string check
    return target.strip() == current.strip()

def start_server():
    kill_port_8000() 
    
    print(f"Starting MCP Server: {SERVER_SCRIPT}")
    process = subprocess.Popen([PYTHON_EXECUTABLE, SERVER_SCRIPT])
    
    print("Waiting for server to start...")
    for i in range(30):
        try:
            resp = requests.get(MCP_SERVER_URL + "/", timeout=1)
            if resp.status_code == 200:
                print("\nServer is ready!")
                return process
        except requests.exceptions.ConnectionError:
            time.sleep(1)
            if i % 5 == 0: print(".", end="", flush=True)
        except Exception as e:
            print(f"Server check error: {e}")
            
    print("\nServer failed to respond. Check terminal output above for errors.")
    if process.poll() is not None:
        print(f"Server process exited with code {process.returncode}")
    return None

def execute_actions(actions, max_limit=50):
    if len(actions) > max_limit: return False, f"Too many actions planned ({len(actions)} > {max_limit})"
    
    count = 0
    for action in actions:
        count += 1
        if count > max_limit: return False, f"Action execution limit exceeded ({count} > {max_limit})"
        
        tool = action.get("tool")
        try:
            if tool == "select":
                requests.post(f"{MCP_SERVER_URL}/tools/select", params={"category": action["category"], "value": str(action["value"])})
            elif tool == "click":
                requests.post(f"{MCP_SERVER_URL}/draw/click", params={"x": action["x"], "y": action["y"]})
            elif tool == "drag":
                requests.post(f"{MCP_SERVER_URL}/draw/drag", params={
                    "start_x": action["start_x"], "start_y": action["start_y"], 
                    "end_x": action["end_x"], "end_y": action["end_y"]
                })
            time.sleep(0.1)
        except Exception: pass
        
    return True, "Completed"

def run_tutor_session():
    print("\n=== ChemGrid AI Tutor: Adaptive Learning Mode ===\n")
    mutator = ActionMutator()
    
    for level in range(1, 11):
        print(f"\n[Level {level}] Initializing...")
        try:
            resp = requests.post(f"{MCP_SERVER_URL}/molecule/generate", params={"level": level})
            if resp.status_code != 200: 
                print(f"API Error: {resp.text}")
                continue
            data = resp.json()
            molecule = data["molecule"]
            current_actions = molecule.get("actions", [])
            target_smiles = molecule["smiles"]
            
            baseline_count = len(current_actions)
            action_limit = max(20, baseline_count * 3) 
            
            print(f"Target: {molecule['name']} ({target_smiles})")
            print(f"Baseline Actions: {baseline_count}, Limit: {action_limit}")
            
        except Exception as e:
            print(f"Init Error: {e}")
            break
            
        attempt = 0
        while True:
            attempt += 1
            print(f"\n[Level {level}] Attempt #{attempt}")
            requests.post(f"{MCP_SERVER_URL}/canvas/reset")
            time.sleep(1)
            
            capture_screen(f"L{level}_A{attempt}_start")

            if attempt > 1:
                print(" -> Applying mutation strategy...")
                current_actions = mutator.mutate(current_actions)

            print(f" -> Executing {len(current_actions)} actions...")
            success, message = execute_actions(current_actions, max_limit=action_limit)
            
            # Wait for file update
            time.sleep(1) 
            
            if not success:
                print(f" -> ABORTED: {message}. Resetting...")
                capture_screen(f"L{level}_A{attempt}_abort")
                log_attempt(level, attempt, current_actions, target_smiles, "N/A", False, reason=message)
                requests.post(f"{MCP_SERVER_URL}/canvas/reset")
                time.sleep(1)
                continue

            print(" -> Validating...")
            capture_screen(f"L{level}_A{attempt}_end")
            
            # Real Validation using File
            current_smiles, atom_count = get_current_smiles()
            print(f"    Current Canvas SMILES: {current_smiles} (Atoms: {atom_count})")
            
            is_success = validate_smiles(target_smiles, current_smiles)
            
            if atom_count == 0 and len(current_actions) > 0:
                 print("    WARNING: Canvas is empty despite actions executed.")
                 is_success = False

            log_attempt(level, attempt, current_actions, target_smiles, current_smiles, is_success, reason="Validation Failed" if not is_success else "")
            
            if is_success:
                print(" -> SMILES Matched. Verifying Lewis Structure...")
                # [Fix] Lewis 구조 모드로 전환하여 시각적 검증 수행
                try:
                    requests.post(f"{MCP_SERVER_URL}/tools/select", params={"category": "mode", "value": "Lewis"})
                    time.sleep(2) # 렌더링 대기
                    
                    lewis_capture_path = f"{CAPTURE_DIR}/L{level}_A{attempt}_Lewis_{datetime.now().strftime('%H%M%S')}.png"
                    ImageGrab.grab().save(lewis_capture_path)
                    print(f"    Lewis Structure Captured: {lewis_capture_path}")
                    
                    # [TODO] 여기서 실제 이미지 비교(Image comparison) 로직 수행 (현재는 캡처 성공 시 통과 처리)
                    # if not compare_images(lewis_capture_path, reference_image):
                    #     print("    Visual Verification Failed.")
                    #     is_success = False
                    
                    # 다시 그리기 모드로 복귀
                    requests.post(f"{MCP_SERVER_URL}/tools/select", params={"category": "mode", "value": "Drawing"})
                    time.sleep(1)
                    
                except Exception as e:
                    print(f"    Verification Error: {e}")
                    # 에러 발생 시에도 일단 진행 (UI 문제일 수 있음)

                if is_success:
                    print(f"SUCCESS! Level {level} completed.")
                    break
            else:
                print(f"FAILURE. Retrying...")
                time.sleep(1)
        time.sleep(1)

def main():
    if not ensure_chemgrid_running():
        print("WARNING: Could not start ChemGrid automatically.")
    
    server_proc = start_server()
    
    if server_proc:
        try:
            run_tutor_session()
        except KeyboardInterrupt:
            print("\nSession interrupted.")
        finally:
            print("Stopping server...")
            server_proc.terminate()
            kill_port_8000()
    else:
        print("Could not start server. Aborting.")

if __name__ == "__main__":
    main()
